import type { TeamMember } from "@/types/team"

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "1",
    name: "Robert Blaylock",
    role: "Full Stack Developer",
    email: "rblaylock@banyanlabs.io",
    phone: "+1 (731) 300-8706",
    joinDate: "2025-05-12",
    avatar: "/placeholder.svg?height=200&width=200&text=RB",
    vision:
      "I aim to build positive, functional apps while fostering strong teamwork, collaboration, and high morale throughout the development process.",
    bio: "Robert is a full stack developer with strong skills in JavaScript, Tailwind CSS, and React. He also brings valuable project management experience, enabling us to deliver efficient, well-organized solutions across both front-end and back-end development.",
    portfolio: "https://www.rblaylock.dev",
    linkedin: "https://www.linkedin.com/in/rblaylock286",
    github: "https://github.com/rblaylock-dev",
    skills: ["React", "TypeScript", "Express", "Next.js", "Tailwind CSS", "MongoDB", "Authentication"],
    projects: [
      {
        name: "To-Do List with Authentication",
        description: "A full-stack to-do list application with user authentication, allowing users to create, update, and delete tasks securely.",
        url: "https://github.com/RBlaylock-Dev/BackendFinals",
        tech: ["React", "Node.js","Bcrypt", "MongoDB","Express"],
      },
      {
        name: "ShoeStyle Landing Page",
        description: "A modern, responsive landing page for a premium shoe store with product showcase.",
        url: "https://ojt-practice-project.vercel.app/",
        tech: ["React", "TypeScript", "Tailwind CSS"],
      },
    ],
    location: "Counce, TN",
    timezone: "CST (UTC-6)",
  },
  {
    id: "2",
    name: "Jessica Sharp",
    role: "Front End Developer",
    email: "jsharp@banyanlabs.io",
    phone: "+1 (731) 803-2422",
    joinDate: "2025-05-12",
    avatar: "/placeholder.svg?height=200&width=200&text=JS",
    vision:
      "To create beautiful, accessible interfaces that empower users and make technology feel magical for everyone.",
    bio: "Jessica Sharp is a fast-learning front end web developer with strong management experience, committed to building innovative digital solutions and continuously growing her skills in a dynamic tech environment.",
    portfolio: "https://jsharp2023.github.io/Portfolio-2024/",
    linkedin: "https://www.linkedin.com/in/jessica-sharp-3b4069313/",
    github: "https://github.com/jsharp2023?tab=repositories",
    skills: ["Node.js", "Bootstrap", "CSS", "TailwindCSS", "Docker", "Java Script", "Auth0", "HTML5", "React", "TypeScript", "MongoDB"],
    projects: [
      {
        name: "SoberBook",
        description: "Social media platform for individuals in recovery, focusing on community support and resources.",
        url: "https://jsharp2023.github.io/soberbook/#/",
        tech: ["React.js", "Auth0", "TailwindCSS", "API",],
      },
      {
        name: "NeverForGiftMe",
        description: "A gift recommendation app that uses an API to suggest personalized gifts based on user preferences.",
        url: "https://jsharp2023.github.io/NeverForGiftMe/",
        tech: ["HTML", "CSS", "JS", "React", "API"],
      },
    ],
    location: "Counce, TN",
    timezone: "CST (UTC-6)",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    role: "Designer",
    email: "emily@company.com",
    phone: "+1 (555) 345-6789",
    joinDate: "2023-03-10",
    avatar: "/placeholder.svg?height=200&width=200&text=ER",
    vision:
      "Crafting meaningful design solutions that bridge the gap between human needs and technological possibilities.",
    bio: "Emily is a creative UX/UI designer with a background in psychology. She brings a user-centered approach to every project, ensuring that design decisions are backed by research and empathy. She's passionate about accessibility and inclusive design.",
    portfolio: "https://emilyrodriguez.design",
    linkedin: "https://linkedin.com/in/emilyrodriguez",
    github: "https://github.com/emilydesign",
    skills: ["Figma", "Adobe Creative Suite", "User Research", "Prototyping", "Design Systems", "Accessibility"],
    projects: [
      {
        name: "Mobile Banking App",
        description: "Complete redesign of a banking app focusing on accessibility and user experience.",
        url: "https://banking-redesign.com",
        tech: ["Figma", "Principle", "User Testing", "Accessibility Audit"],
      },
      {
        name: "Healthcare Dashboard",
        description: "Dashboard design for healthcare professionals to manage patient data efficiently.",
        url: "https://healthcare-ui.com",
        tech: ["Sketch", "InVision", "User Research", "Wireframing"],
      },
    ],
    location: "Austin, TX",
    timezone: "CST (UTC-6)",
  },
  {
    id: "4",
    name: "David Kim",
    role: "Product Manager",
    email: "david@company.com",
    phone: "+1 (555) 456-7890",
    joinDate: "2022-08-05",
    avatar: "/placeholder.svg?height=200&width=200&text=DK",
    vision:
      "Connecting user insights with business goals to create products that truly matter and drive positive change.",
    bio: "David is a strategic product manager with a track record of launching successful products. He excels at translating complex user needs into actionable product roadmaps. David has an MBA and loves analyzing market trends and user behavior.",
    portfolio: "https://davidkim.pm",
    linkedin: "https://linkedin.com/in/davidkim",
    github: "https://github.com/davidkim",
    skills: ["Product Strategy", "User Research", "Data Analysis", "Agile", "Roadmapping", "Stakeholder Management"],
    projects: [
      {
        name: "SaaS Platform Launch",
        description: "Led the successful launch of a B2B SaaS platform that acquired 10K+ users in 6 months.",
        url: "https://saas-platform.com",
        tech: ["Product Strategy", "Market Research", "Analytics", "A/B Testing"],
      },
      {
        name: "Mobile App Redesign",
        description: "Product strategy and execution for a complete mobile app redesign increasing retention by 40%.",
        url: "https://mobile-redesign.com",
        tech: ["User Research", "Product Analytics", "Roadmapping", "Cross-functional Leadership"],
      },
    ],
    location: "New York, NY",
    timezone: "EST (UTC-5)",
  },
  {
    id: "5",
    name: "Lisa Thompson",
    role: "Designer",
    email: "lisa@company.com",
    phone: "+1 (555) 567-8901",
    joinDate: "2023-05-22",
    avatar: "/placeholder.svg?height=200&width=200&text=LT",
    vision:
      "Designing inclusive experiences that celebrate diversity and make technology accessible to all communities.",
    bio: "Lisa is a passionate designer focused on creating inclusive and accessible digital experiences. With a background in graphic design and human-computer interaction, she brings both aesthetic sensibility and technical understanding to her work.",
    portfolio: "https://lisathompson.design",
    linkedin: "https://linkedin.com/in/lisathompson",
    github: "https://github.com/lisadesign",
    skills: ["UI/UX Design", "Accessibility", "Design Systems", "Branding", "Illustration", "Motion Design"],
    projects: [
      {
        name: "Accessibility Toolkit",
        description: "Comprehensive design toolkit for creating accessible digital experiences.",
        url: "https://accessibility-toolkit.com",
        tech: ["Figma", "Accessibility Guidelines", "Color Theory", "Typography"],
      },
      {
        name: "Brand Identity System",
        description: "Complete brand identity and design system for a sustainable fashion startup.",
        url: "https://brand-identity.com",
        tech: ["Adobe Illustrator", "Brand Strategy", "Design Systems", "Style Guides"],
      },
    ],
    location: "Portland, OR",
    timezone: "PST (UTC-8)",
  },
  {
    id: "6",
    name: "Alex Martinez",
    role: "Frontend Developer",
    email: "alex@company.com",
    phone: "+1 (555) 678-9012",
    joinDate: "2023-02-14",
    avatar: "/placeholder.svg?height=200&width=200&text=AM",
    vision:
      "Pushing the boundaries of web technology to create immersive, performant applications that inspire and delight.",
    bio: "Alex is an innovative frontend developer who loves experimenting with cutting-edge web technologies. Specializing in performance optimization and modern JavaScript frameworks, Alex creates fast, engaging user experiences.",
    portfolio: "https://alexmartinez.dev",
    linkedin: "https://linkedin.com/in/alexmartinez",
    github: "https://github.com/alexmartinez",
    skills: ["React", "Vue.js", "WebGL", "Performance Optimization", "PWAs", "Web Components"],
    projects: [
      {
        name: "3D Portfolio Website",
        description: "Interactive 3D portfolio showcasing web development projects with WebGL animations.",
        url: "https://3d-portfolio.com",
        tech: ["Three.js", "WebGL", "React", "GSAP"],
      },
      {
        name: "Progressive Web App",
        description: "High-performance PWA with offline capabilities and native-like experience.",
        url: "https://pwa-demo.com",
        tech: ["React", "Service Workers", "IndexedDB", "Web App Manifest"],
      },
    ],
    location: "Miami, FL",
    timezone: "EST (UTC-5)",
  },
]

export const ROLES = [
  "Frontend Developer",
  "Backend Developer",
  "Designer",
  "Product Manager",
  "DevOps Engineer",
  "Data Scientist",
  "QA Engineer",
] as const

export const SKILLS = [
  "React",
  "TypeScript",
  "Node.js",
  "Python",
  "JavaScript",
  "CSS",
  "HTML",
  "Vue.js",
  "Angular",
  "Next.js",
  "Express",
  "PostgreSQL",
  "MongoDB",
  "AWS",
  "Docker",
  "Kubernetes",
  "Figma",
  "Adobe Creative Suite",
] as const
